# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-02 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name=b'user',
        ),
        migrations.AddField(
            model_name='customer',
            name='first_name',
            field=models.CharField(default=b'', max_length=150),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name=b'business',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name=b'siren',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name=b'quantity',
            field=models.IntegerField(),
        ),
    ]
