# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-02 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20181002_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='orders',
            field=models.ManyToManyField(through='main_app.Order', to='main_app.Product'),
        ),
    ]
