# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-05 09:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20181004_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Bill')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Product')),
            ],
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='orders',
        ),
        migrations.AlterField(
            model_name='customer',
            name='logo',
            field=models.ImageField(null=True, upload_to=b'user'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=[b'first_name', b'last_name']),
        ),
    ]
