# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-05 09:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20181005_0929'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='QuotationLine',
        ),
    ]
