# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-05 10:16
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20181005_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='fax_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default="00000", max_length=128),
            preserve_default=False,
        ),
    ]
