# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-08 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20181005_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.SlugField(max_length=8),
        ),
    ]
