# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-11 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20181008_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='status',
            field=models.CharField(default=b'A relancer', max_length=200),
        ),
    ]
