# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-15 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_quotation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[(b'A relancer', b'A relancer'), (b'En cours', b'En cours'), (b'A convertir', b'A convertir')], default=b'A relancer', max_length=200),
        ),
    ]
